### ISSUE TITLE
Dependencies need to be explicictly installed and loaded

### ISSUE THREAD

**Issue by egbendito** [ropensci/nasapower#72]
**Describe the bug**
Trying to make a request using get_power() function results in an error message:

`Error: 2011-01-01 is not a valid entry for date. Enter as YYYY-MM-DD.`

After manually installing and loading lubridate package the request is successful.

**Code to Reproduce**
```
install.packages("nasapower")
nasapower::get_power(community = "AG",
                     lonlat = c(5.55,7.85),
                     pars = c("T2M_MAX","T2M_MIN"),
                     dates = c("2011-01-01", "2011-01-10"),
                     temporal_api = "DAILY")
install.packages("lubridate")
library(lubridate)
nasapower::get_power(community = "AG",
                     lonlat = c(5.55,7.85),
                     pars = c("T2M_MAX","T2M_MIN"),
                     dates = c("2011-01-01", "2011-01-10"),
                     temporal_api = "DAILY")
```
**OS and R versions (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa)
 - R Version: R version 4.1.3 (2022-03-10)

**Additional context**
The R session works on a Jupyter Lab

**Comment by adamhsparks** [comment]
Lubridate is listed in the Imports file girls of the DESCRIPTION so I’m not sure what causes your issue. 

How did you install nasapower?

**Comment by egbendito** [comment]
Thanks for the package and the reply! 

I installed it using `install.packages("nasapower")`.

I believe the CRAN repository is

```
> options('repos')
$repos
                                                            CRAN 
"https://cran.r-project.org"
```

**Comment by adamhsparks** [comment]
Sorry, but I don't know what the issue is, but it's not a bug with _nasapower_, else it wouldn't be passing checks here on GitHub or CRAN because it wouldn't install correctly for those systems. You can see its passing checks here on GitHub Actions: https://github.com/ropensci/nasapower/actions/runs/2587543397.

Additionally, since I just upgraded my local R installation, I had to reinstall all my R packages. When I installed _nasapower_; _lubridate_ was automatically installed.
